# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanalysis',
            name='result_status',
            field=models.CharField(default=b'queued', max_length=32),
        ),
    ]
