# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellc1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellc1task',
            name='cell_ratio',
        ),
        migrations.RemoveField(
            model_name='cellc1task',
            name='count_max',
        ),
        migrations.RemoveField(
            model_name='cellc1task',
            name='count_min',
        ),
        migrations.AddField(
            model_name='cellc1task',
            name='cell_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
