# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellc1', '0002_auto_20160510_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellc1task',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'Cell C1 Task'},
        ),
    ]
