# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('file_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='fs.File')),
                ('status', models.CharField(default='queued', max_length=32)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('dequeued', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=32)),
                ('uploaded_filetype', models.CharField(blank=True, max_length=10)),
                ('uploaded_image', models.ImageField(blank=True, max_length=255, upload_to=b'')),
                ('result_image', models.ImageField(blank=True, max_length=255, upload_to=b'')),
                ('uploaded_display', models.ImageField(blank=True, max_length=255, upload_to=b'')),
                ('result_display', models.ImageField(blank=True, max_length=255, upload_to=b'')),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('cell_ratio', models.FloatField(blank=True, null=True)),
                ('count_min', models.FloatField(blank=True, null=True)),
                ('count_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
                'verbose_name': 'Cell C2 Task',
            },
            bases=('fs.file',),
        ),
    ]
