# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cell', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellC2Task',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('dequeued', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=32)),
                ('uploaded_filename', models.CharField(max_length=255)),
                ('uploaded_filetype', models.CharField(max_length=10)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('cell_ratio', models.FloatField(blank=True, null=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cell.Folder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
                'verbose_name': 'Cell C2 Task',
            },
        ),
    ]
