# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellC2Task',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cell.File')),
                ('status', models.CharField(default='queued', max_length=32)),
                ('dequeued', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=32)),
                ('uploaded_filetype', models.CharField(max_length=10)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='content', to='cell.File')),
                ('cell_ratio', models.FloatField(blank=True, null=True)),
                ('count_min', models.FloatField(blank=True, null=True)),
                ('count_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
                'verbose_name': 'Cell C2 Task',
            },
            bases=('cell.file',),
        ),
    ]
