# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellc2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cell_ratio',
        ),
        migrations.RemoveField(
            model_name='task',
            name='count_max',
        ),
        migrations.RemoveField(
            model_name='task',
            name='count_min',
        ),
    ]
