# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='number_of_ovum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovumgrade',
            name='grade',
            field=models.CharField(default='A', max_length=32),
        ),
    ]
