# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icsi', '0003_auto_20160223_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovumgrade',
            name='status',
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='description',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='mother_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='number_of_A',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='number_of_B',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='number_of_C',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='number_of_D',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='icsiimageanalysis',
            name='number_of_E',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ovumgrade',
            name='ovum_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovumgrade',
            name='parent_imageanalysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ovums', to='icsi.ICSIImageAnalysis'),
        ),
    ]
