# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='app.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('enqueue_date', models.DateTimeField(auto_now_add=True)),
                ('dequeue_date', models.DateTimeField(null=True)),
                ('result', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(null=True)),
                ('result_status', models.CharField(default=b'WAITING', max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('user_filename', models.CharField(max_length=255)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Folder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Analysis',
            },
        ),
    ]
