# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160203_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='user',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='ImageAnalysis',
        ),
    ]
