# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imageanalysis_result_outerr'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='mesh_number',
            field=models.IntegerField(null=True),
        ),
    ]
