# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsi', '0002_auto_20160223_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icsiimageanalysis',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='icsifolder',
            name='method',
            field=models.CharField(default='ICSI', max_length=32),
        ),
    ]
