# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celln1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celln1task',
            old_name='cell_count',
            new_name='soma_count',
        ),
    ]
