# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cellcount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellcountFolder',
            fields=[
                ('folder_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(default=b'Cellcount', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_folders', to='cellcount.CellcountFolder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CellcountImageAnalysis',
            fields=[
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('enqueue_date', models.DateTimeField(auto_now_add=True)),
                ('dequeue_date', models.DateTimeField(null=True)),
                ('result_date', models.DateTimeField(null=True)),
                ('result_status', models.CharField(default=b'queued', max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('user_filename', models.CharField(max_length=255)),
                ('result', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Analysis',
            },
        ),
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='imageanalysis',
            name='user',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='ImageAnalysis',
        ),
    ]
