# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20160203_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellC1Analysis',
            fields=[
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('enqueue_date', models.DateTimeField(auto_now_add=True)),
                ('dequeue_date', models.DateTimeField(null=True)),
                ('result', models.TextField(blank=True)),
                ('result_outerr', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(null=True)),
                ('result_status', models.CharField(default=b'queued', max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('user_filename', models.CharField(max_length=255)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Folder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cell C1 Analysis',
            },
        ),
    ]
